version: '3.9'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 3000:3000

